import { z } from "zod";

const envSchema = z.object({
  DATABASE_URL: z.string().min(1, "DATABASE_URL is required."),
  BETTER_AUTH_SECRET: z.string().default("dev-secret"),
  BETTER_AUTH_URL: z.string().url().default("http://localhost:3000"),
  APP_BASE_URL: z.string().url().default("http://localhost:3000"),
  APP_ENV: z.enum(["development", "test", "production"]).default("development"),
  ENCRYPTION_KEY: z.string().min(1, "ENCRYPTION_KEY is required."),
  LINUX_DO_CLIENT_ID: z.string().optional(),
  LINUX_DO_CLIENT_SECRET: z.string().optional(),
  S3_ENDPOINT: z.string().optional(),
  S3_REGION: z.string().optional(),
  S3_BUCKET: z.string().optional(),
  S3_ACCESS_KEY_ID: z.string().optional(),
  S3_SECRET_ACCESS_KEY: z.string().optional(),
  GROK_API_URL: z.string().url().optional().or(z.literal("")),
  GROK_API_KEY: z.string().optional(),
  GROK_MODEL: z.string().optional(),
  TAVILY_API_URL: z.string().url().optional().or(z.literal("")),
  TAVILY_API_KEY: z.string().optional(),
  FIRECRAWL_API_URL: z.string().url().optional().or(z.literal("")),
  FIRECRAWL_API_KEY: z.string().optional(),
  GROK_RETRY_MAX_ATTEMPTS: z.coerce.number().int().positive().default(2),
  GROK_RETRY_MULTIPLIER: z.coerce.number().positive().default(2),
  GROK_RETRY_MAX_WAIT: z.coerce.number().positive().default(30000),
});

export const env = envSchema.parse({
  DATABASE_URL: process.env.DATABASE_URL,
  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
  APP_BASE_URL: process.env.APP_BASE_URL,
  APP_ENV: process.env.APP_ENV,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
  LINUX_DO_CLIENT_ID: process.env.LINUX_DO_CLIENT_ID,
  LINUX_DO_CLIENT_SECRET: process.env.LINUX_DO_CLIENT_SECRET,
  S3_ENDPOINT: process.env.S3_ENDPOINT,
  S3_REGION: process.env.S3_REGION,
  S3_BUCKET: process.env.S3_BUCKET,
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
  GROK_API_URL: process.env.GROK_API_URL,
  GROK_API_KEY: process.env.GROK_API_KEY,
  GROK_MODEL: process.env.GROK_MODEL,
  TAVILY_API_URL: process.env.TAVILY_API_URL,
  TAVILY_API_KEY: process.env.TAVILY_API_KEY,
  FIRECRAWL_API_URL: process.env.FIRECRAWL_API_URL,
  FIRECRAWL_API_KEY: process.env.FIRECRAWL_API_KEY,
  GROK_RETRY_MAX_ATTEMPTS: process.env.GROK_RETRY_MAX_ATTEMPTS,
  GROK_RETRY_MULTIPLIER: process.env.GROK_RETRY_MULTIPLIER,
  GROK_RETRY_MAX_WAIT: process.env.GROK_RETRY_MAX_WAIT,
});

export const isProduction = env.APP_ENV === "production";
